# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: sqlite3
  host: localhost
  username: postgres
  password: <%= ENV['DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3

production:
  adapter: postgresql
  pool: 10
  reaping_frequency: 10
  reconnect: true
  url: <%= ENV['APPSDECK_POSTGRESQL_URL'] %>
